<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-QFKR4O5H" ignored="0" name="Identify Courses in Opera" tests="20" failures="7" timestamp="05 Oct 2020 08:02:19 GMT" time="444.808" errors="0">
  <testcase name="searchTest" time="117.921" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.151" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="12.409" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="21.751" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="21.489" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.513" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="10.897" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="27.326" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="17.156" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="19.793" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="16.663" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="15.474" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="31.331" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="15.074" classname="TestCases.IdentifyCoursesTest">
    <failure type="java.lang.AssertionError" message="Error message NOT displayed, which is a failure!">
      <![CDATA[java.lang.AssertionError: Error message NOT displayed, which is a failure!
at BaseClasses.BaseTestClass.reportFail(BaseTestClass.java:174)
at PageClasses.CourseraForCampusPage.fillAndSubmitForm(CourseraForCampusPage.java:117)
at TestCases.IdentifyCoursesTest.formTest(IdentifyCoursesTest.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- formTest -->
  <testcase name="formTest" time="11.689" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="10.886" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="10.63" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="15.102" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="19.489" classname="TestCases.IdentifyCoursesTest"/>
  <testcase name="formTest" time="13.05" classname="TestCases.IdentifyCoursesTest"/>
</testsuite> <!-- Identify Courses in Opera -->
